# Retell CLI - Production Deployment Workflow
#
# Deploys changed agents to production workspace when merged to production branch.
# Requires agents to exist in staging first.
# Manual trigger requires typing "PRODUCTION" to confirm.
#
# Required secrets:
#   - RETELL_STAGING_API_KEY
#   - RETELL_PRODUCTION_API_KEY

name: Deploy to Production

on:
  push:
    branches: [production]
    paths:
      - 'agents/**'
      - 'prompts/**'

  workflow_dispatch:
    inputs:
      agent:
        description: 'Agent to deploy (leave empty for all changed)'
        required: false
        type: string
      confirm:
        description: 'Type PRODUCTION to confirm'
        required: true
        type: string

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    if: github.event_name == 'push' || github.event.inputs.confirm == 'PRODUCTION'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Retell CLI
        run: npm install -g @heya/retell-cli

      - name: Generate workspace config
        env:
          RETELL_STAGING_API_KEY: ${{ secrets.RETELL_STAGING_API_KEY }}
          RETELL_PRODUCTION_API_KEY: ${{ secrets.RETELL_PRODUCTION_API_KEY }}
        run: |
          cat > workspaces.json << EOF
          {
            "staging": {
              "api_key": "$RETELL_STAGING_API_KEY",
              "name": "Staging",
              "base_url": "https://api.retellai.com"
            },
            "production": {
              "api_key": "$RETELL_PRODUCTION_API_KEY",
              "name": "Production",
              "base_url": "https://api.retellai.com"
            }
          }
          EOF

      - name: Determine agents to deploy
        id: agents
        run: |
          if [ -n "${{ github.event.inputs.agent }}" ]; then
            echo "agents=${{ github.event.inputs.agent }}" >> $GITHUB_OUTPUT
          else
            changed=$(git diff --name-only HEAD~1 HEAD -- agents/ | cut -d'/' -f2 | sort -u | tr '\n' ' ')
            echo "agents=$changed" >> $GITHUB_OUTPUT
          fi

      - name: Verify staging deployment
        run: |
          for agent in ${{ steps.agents.outputs.agents }}; do
            if [ ! -f "agents/$agent/staging.json" ]; then
              echo "::error::$agent not deployed to staging"
              exit 1
            fi
          done

      - name: Deploy agents
        run: |
          for agent in ${{ steps.agents.outputs.agents }}; do
            if [ -d "agents/$agent" ]; then
              echo "Deploying to PRODUCTION: $agent"
              retell push "$agent" -w production
            fi
          done

      - name: Commit metadata
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add agents/*/production.json
          if ! git diff --staged --quiet; then
            git commit -m "chore: update production metadata

            Deployed by: ${{ github.actor }}
            Commit: ${{ github.sha }}"
            git push
          fi
