# Retell CLI - Drift Detection Workflow
#
# Detects configuration drift (changes made via Retell Console instead of Git).
# Runs every 6 hours or on manual trigger.
# Creates a GitHub issue when drift is detected.
#
# Required secrets:
#   - RETELL_STAGING_API_KEY
#   - RETELL_PRODUCTION_API_KEY

name: Drift Detection

on:
  schedule:
    - cron: '0 */6 * * *'

  workflow_dispatch:
    inputs:
      workspace:
        description: 'Workspace to check'
        required: false
        default: 'both'
        type: choice
        options:
          - staging
          - production
          - both

permissions:
  contents: read
  issues: write

jobs:
  detect:
    name: Detect Drift
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Retell CLI
        run: npm install -g @heya/retell-cli

      - name: Generate workspace config
        env:
          RETELL_STAGING_API_KEY: ${{ secrets.RETELL_STAGING_API_KEY }}
          RETELL_PRODUCTION_API_KEY: ${{ secrets.RETELL_PRODUCTION_API_KEY }}
        run: |
          cat > workspaces.json << EOF
          {
            "staging": {
              "api_key": "$RETELL_STAGING_API_KEY",
              "name": "Staging",
              "base_url": "https://api.retellai.com"
            },
            "production": {
              "api_key": "$RETELL_PRODUCTION_API_KEY",
              "name": "Production",
              "base_url": "https://api.retellai.com"
            }
          }
          EOF

      - name: Check for drift
        id: drift
        run: |
          workspace="${{ github.event.inputs.workspace || 'both' }}"
          drifted=""

          check_workspace() {
            ws=$1
            for agent_dir in agents/*/; do
              agent=$(basename "$agent_dir")
              if [ -f "$agent_dir/${ws}.json" ]; then
                if retell diff "$agent" -w "$ws" 2>&1 | grep -q "Conflicts Detected"; then
                  drifted="$drifted $agent($ws)"
                  echo "::warning::Drift: $agent in $ws"
                fi
              fi
            done
          }

          if [ "$workspace" = "staging" ] || [ "$workspace" = "both" ]; then
            check_workspace staging
          fi
          if [ "$workspace" = "production" ] || [ "$workspace" = "both" ]; then
            check_workspace production
          fi

          echo "drifted=$drifted" >> $GITHUB_OUTPUT

      - name: Create issue
        if: steps.drift.outputs.drifted != ''
        uses: actions/github-script@v7
        with:
          script: |
            const drifted = '${{ steps.drift.outputs.drifted }}'.trim();

            const body = `## Configuration Drift Detected

The following agents have been modified outside of Git:

**${drifted}**

### Resolution Options

**Keep Git version (overwrite remote):**
\`\`\`bash
retell push <agent> -w <workspace> --force
\`\`\`

**Accept remote changes (update Git):**
\`\`\`bash
retell pull <agent> -w <workspace> --force
git add agents/<agent>/
git commit -m "chore: sync drift from console"
git push
\`\`\`

---
*Detected by Drift Detection workflow*`;

            // Check for existing open issue
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'drift-detection'
            });

            if (issues.length > 0) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issues[0].number,
                body: `## Updated\n\n${body}`
              });
            } else {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'Configuration Drift Detected',
                body: body,
                labels: ['drift-detection']
              });
            }
