# Retell CLI - PR Validation Workflow
#
# Validates agent configurations and checks for conflicts before merge.
# Triggers on PRs to staging or production branches.
#
# Required secrets:
#   - RETELL_STAGING_API_KEY
#   - RETELL_PRODUCTION_API_KEY

name: Validate

on:
  pull_request:
    branches: [staging, production]
    paths:
      - 'agents/**'
      - 'prompts/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    name: Validate & Check Conflicts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Retell CLI
        run: npm install -g @heya/retell-cli

      - name: Generate workspace config
        env:
          RETELL_STAGING_API_KEY: ${{ secrets.RETELL_STAGING_API_KEY }}
          RETELL_PRODUCTION_API_KEY: ${{ secrets.RETELL_PRODUCTION_API_KEY }}
        run: |
          cat > workspaces.json << EOF
          {
            "staging": {
              "api_key": "$RETELL_STAGING_API_KEY",
              "name": "Staging",
              "base_url": "https://api.retellai.com"
            },
            "production": {
              "api_key": "$RETELL_PRODUCTION_API_KEY",
              "name": "Production",
              "base_url": "https://api.retellai.com"
            }
          }
          EOF

      - name: Detect changed agents
        id: changed
        run: |
          changed_files=$(git diff --name-only origin/${{ github.base_ref }}...HEAD -- agents/)
          agents=""
          for file in $changed_files; do
            agent=$(echo "$file" | cut -d'/' -f2)
            if [ -d "agents/$agent" ] && [[ ! "$agents" =~ "$agent" ]]; then
              agents="$agents $agent"
            fi
          done
          echo "agents=$agents" >> $GITHUB_OUTPUT
          echo "Changed agents:$agents"

      - name: Check for conflicts
        id: conflicts
        run: |
          workspace="${{ github.base_ref }}"
          conflicts=""
          for agent in ${{ steps.changed.outputs.agents }}; do
            echo "Checking: $agent"
            if retell diff "$agent" -w "$workspace" 2>&1 | grep -q "Conflicts Detected"; then
              conflicts="$conflicts $agent"
              echo "::warning::Conflict detected: $agent"
            fi
          done
          echo "conflicts=$conflicts" >> $GITHUB_OUTPUT
          if [ -n "$conflicts" ]; then
            echo "::error::Conflicts found:$conflicts"
            exit 1
          fi

      - name: Post PR comment
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const conflicts = '${{ steps.conflicts.outputs.conflicts }}'.trim();
            const agents = '${{ steps.changed.outputs.agents }}'.trim();
            const workspace = '${{ github.base_ref }}';

            let body;
            if (conflicts) {
              body = `## ⚠️ Conflicts Detected

**Agents with conflicts:** ${conflicts}

Someone modified these agents via the Retell Console.

### Resolution Options

**Keep your changes (overwrite remote):**
\`\`\`bash
retell push <agent> -w ${workspace} --force
\`\`\`

**Accept remote changes (update local):**
\`\`\`bash
retell pull <agent> -w ${workspace} --force
git add agents/<agent>/
git commit -m "chore: sync remote changes"
git push
\`\`\``;
            } else {
              body = `## ✅ Validation Passed

**Agents to deploy:** ${agents || 'none'}

Merge this PR to deploy to **${workspace}**.`;
            }

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });
